### ISSUE TITLE
Android 2.3.3

### ISSUE THREAD

**Issue by lionscribe** [androidsx/rate-me#66]
You say that it supports Android 2.3+
You have the manifest say android:minSdkVersion="10"
But really it only supports 3.0, as DialogRateMe extends DialogFragment, which was introduced in 3.0
so it should be android:minSdkVersion="11"
You can use the android.support.v4.app.DialogFragment, but that will necessitate including the support library.

**Comment by espinchi** [comment]
Indeed, 3.0 is the real minimum version, as you point out. @pocho23 just updated the doc and the code to reflect this: https://github.com/androidsx/rate-me/commit/fc04fcd2deb807c451829a9810e6fbf3d548f151
