### ISSUE TITLE
Failed to resolve compile 'com.androidsx:rate-me:X.Y.'

### ISSUE THREAD

**Issue by paveltech** [androidsx/rate-me#78]
When i add this dependency into my gradle file it show this error Failed to resolve.

**Comment by sanketsangani** [comment]
When i am syc this error comes.What is actual missing??
///
Error:(20, 17) Failed to resolve: com.androidsx:rate-me:X.Y.
<a href="openFile:E:/dwnld/chrome dwnld/github_code/ringdroid-master/ringdroid-master/app/build.gradle">Show inn File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

**Comment by pocho23** [comment]
Try with the last version: `com.androidsx:rate-me:4.0.1`

**Comment by sanketsangani** [comment]
Thanks
its works as charm.
