### ISSUE TITLE
I can't found Dependency

### ISSUE THREAD

**Issue by paveltech** [androidsx/rate-me#80]
When i add  compile 'com.androidsx:rate-me:X.Y.' into my gradle i can't found the dependency my log cat show Error:(50, 17) Failed to resolve: com.androidsx:rate-me:X.Y.
<a href="openFile:/home/lolipop/Studio Project/HindiMovieSongWithRetrofit/app/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

**Comment by pocho23** [comment]
Try with the last version: com.androidsx:rate-me:4.0.3
